version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    hostname: s3
    # https://github.com/localstack/localstack/issues/2631
    # https://github.com/localstack/localstack/pull/3690
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - s3-website.localhost.localstack.cloud
          - ${AWS_S3_BUCKET}.s3.localhost.localstack.cloud
          - ${AWS_S3_BUCKET}.s3-website.localhost.localstack.cloud
    ports:
      - "4566:4566"
    environment:
      - DEBUG=${DEBUG-}
      - SERVICES=s3
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    volumes:
      - "./volumes/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/imgs:/home/localstack/imgs"
      - "./.localstack:/etc/localstack/init/"

  stripe:
    image: stripe/stripe-mock:latest
    ports:
      - "${STRIPE_HOST}:${STRIPE_PORT}:${STRIPE_PORT}"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  embedding:
    image: embedding:latest
    ports:
      - ${EMBEDDING_PORT}:5000

  vector-search:
    image: qdrant/qdrant
    ports:
      # HTTP port
      - ${VSEARCH_HPORT}:6333 # defined in `vector-search.yaml`
      # gRPC port
      - ${VSEARCH_RPORT}:6334 # defined in `vector-search.yaml`
    volumes:
      - "./vector-search.yaml:/qdrant/config/production.yaml"
      - "./collection.json:/qdrant/collection.json"
